Comments deleted
imanol309/mini-proyecto pull request #2
Opened 2020-09-08 21:55 UTC by imanol309

Comments deleted

2020-09-09 17:32 UTC, angerimg approved these changes

2020-09-09 17:32 UTC, angerimg commented on README.MD
> +*It is played by putting the eighteen tiles on the board of the two players, then each player has to be moving until creating a mill (three tiles aligned) to be able to eliminate a tile from your opp
nice!

2020-09-16 14:06 UTC, angerimg requested changes
Cada cosa debe estar en su propio PR

2020-09-17 19:21 UTC, imanol309 commented
¿Podemos hacer la reunión a las 4:00? , Porque estoy en la ciudad y voy a
llegar después de las 3:30.

El mié., 16 de sep. de 2020 10:07 AM, Angeri Martinez Gonzalez <
notifications@github.com> escribió:

> *@angerimg* requested changes on this pull request.
>
> Cada cosa debe estar en su propio PR
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/imanol309/mini-proyecto/pull/2#pullrequestreview-489663009>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOOORFWNL2GEQLNKYJTZ4WDSGDBAJANCNFSM4RASC22Q>
> .
>

2020-09-29 19:19 UTC, angerimg reviewed
Entonces en este los separaste solamente verdad?

2020-09-29 19:39 UTC, imanol309 commented
sii en este solamente lo estoy separando.

El mar., 29 de sep. de 2020 a la(s) 15:19, Angeri Martinez Gonzalez (
notifications@github.com) escribió:

> *@angerimg* commented on this pull request.
>
> Entonces en este los separaste solamente verdad?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/imanol309/mini-proyecto/pull/2#pullrequestreview-498805989>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOOORFQTAV2IVGSESLRE3B3SIIXMFANCNFSM4RASC22Q>
> .
>

2020-10-13 18:34 UTC, angerimg commented
te faltan cambios verdad?

2020-10-13 21:42 UTC, imanol309 commented
NO. yo tengo todos los cambios y mejoras que tu me pediste hechas pero en
un solo repositorio(que se llama comments deleted)
 y tu me dijiste que lo tenía que dividir(porque están todos juntos). Por
eso cree otro repositorio ,en el otro repositorio todavía le faltan cambios
porque me dijiste que lo vaya subiendo uno por uno cada cambio.

El mar., 13 de oct. de 2020 a la(s) 14:34, Angeri Martinez Gonzalez (
notifications@github.com) escribió:

> te faltan cambios verdad?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/imanol309/mini-proyecto/pull/2#issuecomment-707931373>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOOORFVL477NWRD3QC6WPILSKSMS3ANCNFSM4RASC22Q>
> .
>

2020-10-14 14:50 UTC, angerimg commented
creaste diferentes ramas 🤔  leiste lo que te pedi de github?

2020-10-14 15:41 UTC, imanol309 commented
Yo creé otra rama para ir subiendo cada cambio,cuando tu lo acepte lo
mezclo  y después creó otro pull request con los nuevos cambios que faltan
y así lo estoy haciendo.

El mié., 14 de oct. de 2020 a la(s) 10:51, Angeri Martinez Gonzalez (
notifications@github.com) escribió:

> creaste diferentes ramas 🤔 leiste lo que te pedi de github?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/imanol309/mini-proyecto/pull/2#issuecomment-708454974>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOOORFU723OKVUCBJOWUZPTSKW3FVANCNFSM4RASC22Q>
> .
>

2020-10-22 23:49 UTC, closed without merging